---
version: "#{build}"
environment:
  MRUBY_CONFIG: "C:/projects/mruby-io/run_test.rb"

init:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %platform%

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - set PATH=C:\MinGW\bin;C:\MinGW\msys\1.0\bin;%PATH%
  - ruby --version
  - gem --version
  - gcc --version
  - gem install rake
  - git clone --depth 1 https://github.com/mruby/mruby.git
build_script:
  - cd mruby
  - ruby minirake all test --trace --verbose
